language: java
jdk:
  - oraclejdk9
  - openjdk10
  - openjdk11
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8229d26a4f90bcc6cd67
script: mvn test -Dsurefire.useFile=false

# Workaround for SSL issues with Oracle JDK 9
# https://github.com/travis-ci/travis-ci/issues/9368
before_script:
  - rm "${JAVA_HOME}/lib/security/cacerts"
  - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"